### ISSUE TITLE
模仿ajax4sablejs写了一个demo，运行报错

### ISSUE THREAD

**Issue by KingdomWqz** [sablejs/sablejs#22]
output.js 代码如下：
```
ajax({
  url: "https://api.apishop.net/common/weather/get15DaysWeatherByArea",
  method: "GET",
  success: function (response) {
    console.log(response);
  },
});
```
执行 sablejs -i output.js -o output.txt

外层的JS代码
```
function App() {
  useEffect(() => {
    console.log("starting");
    
    const VM = require("sablejs/runtime")();
    const vm = new VM();

    const vGlobal = vm.getGlobal();
    const vConsole = vm.createObject();
    const vLog = vm.createFunction("log", function () {
      const temp = [];
      for (let i = 0; i < arguments.length; i++) {
        temp.push(vm.asString(arguments[i]));
      }

      console.log(...temp);
      return vm.createUndefined();
    });

    const vAjax = vm.createFunction("ajax", function (vOption) {
      const option = {};
      const vUrl = vm.getProperty(vOption, "url");
      const vMethod = vm.getProperty(vOption, "method");
      const vSuccess = vm.getProperty(vOption, "success");

      if (vm.isString(vUrl)) {
        option.url = vm.asString(vUrl);
      }
  
      if (vm.isString(vMethod)) {
        option.method = vm.asString(vMethod);
      }
  
      if (vm.isFunction(vSuccess)) {
        option.success = function(response) {
          vm.call(
            vSuccess,
            vm.createUndefined(),
            vm.createString(response)
          );
        };
      }

      function send(option) {
        let xhr = new XMLHttpRequest();
        xhr.withCredentials = option.withCredentials || false;
        xhr.open((option.method || "GET").toLowerCase(), option.url, true);
      
        xhr.onload = () => {
          if (xhr.readyState === 4 && xhr.status === 200) {
            const response = xhr.responseText;
            console.log(response);
            option.success(response);
          }
        };

        xhr.send(null);
      }
  
      send(option);
      return vm.createUndefined();
    });

    vm.setProperty(vGlobal, "ajax", vAjax);
    vm.setProperty(vConsole, "log", vLog);
    vm.setProperty(vGlobal, "console", vConsole);

    (async () => {
      const resp = await fetch("./output.txt");
      const data = await resp.text();
      vm.run(data);
      vm.destroy();
    })();
  }, []);

  return <div>JS safty</div>;
}
```
运行时报这个错误
```
runtime.js:1 Uncaught TypeError: Cannot read properties of null (reading 'top')
    at ef.call (runtime.js:1:1)
    at Object.option.success (index.js:40:1)
    at XMLHttpRequest.xhr.onload (index.js:57:1)
```

**Comment by KingdomWqz** [comment]
[https://codesandbox.io/embed/jssafty-su1wd?fontsize=14&hidenavigation=1&theme=dark](CodeSandbox)
