### ISSUE TITLE
sablejs -v 报错:  SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by linzp007** [sablejs/sablejs#26]
[root@ecs-ab44 sablejs]# sablejs -v
(node:1978837) UnhandledPromiseRejectionWarning: /usr/local/lib/node_modules/sablejs/node_modules/string-kit/lib/format.js:327
                markupTarget = this.shiftedMarkup?.[ runtime.shift ]?.[ markup ] ;
                                                  ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/sablejs/node_modules/string-kit/lib/string.js:62:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
(node:1978837) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1978837) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by linzp007** [comment]
nodejs版本太低了
