### ISSUE TITLE
在Node环境下运行cli提示`import` 已经被占用

### ISSUE THREAD

**Issue by DynastyKids** [sablejs/sablejs#29]
尝试使用Windows 10来编译（WSL炸了所以没法用），环境是React17+NodeJS16，，提示import关键字被占用了，导致无法编译想要的文件

项目通过create-react-app创建，尝试在目录中运行```sablejs src/components/request.js```
```
[ERROR] compile failed: SyntaxError: The keyword 'import' is reserved (1:0)
    at Parser.<anonymous> (C:\snapshot\sablejs-private-repo\node_modules\acorn\dist\acorn.js:3460:15)
    at Parser.checkUnreserved (C:\snapshot\sablejs-private-repo\node_modules\acorn\dist\acorn.js:3367:12)
    at Parser.parseIdent (C:\snapshot\sablejs-private-repo\node_modules\acorn\dist\acorn.js:3396:12)
    at Parser.parseExprAtom (C:\snapshot\sablejs-private-repo\node_modules\acorn\dist\acorn.js:2759:21)
    at Parser.parseExprSubscripts (C:\snapshot\sablejs-private-repo\node_modules\acorn\dist\acorn.js:2627:21)
    at Parser.parseMaybeUnary (C:\snapshot\sablejs-private-repo\node_modules\acorn\dist\acorn.js:2593:19)
    at Parser.parseExprOps (C:\snapshot\sablejs-private-repo\node_modules\acorn\dist\acorn.js:2520:21)
    at Parser.parseMaybeConditional (C:\snapshot\sablejs-private-repo\node_modules\acorn\dist\acorn.js:2503:21)
    at Parser.parseMaybeAssign (C:\snapshot\sablejs-private-repo\node_modules\acorn\dist\acorn.js:2470:21)
    at Parser.parseExpression (C:\snapshot\sablejs-private-repo\node_modules\acorn\dist\acorn.js:2433:21)
```

**Comment by ErosZy** [comment]
@DynastyKids sablejs only support ecma5.1 spec, `import` keyword is not here. you should use babel to compile your code to ecma5.1.
