### ISSUE TITLE
运行报错 (win10) Download.js:265

### ISSUE THREAD

**Issue by ZengOwen** [sablejs/sablejs#32]
通过淘宝镜像安装后 (npm i sablejs -g --registry=https://registry.npm.taobao.org)

执行 sablejs -i fib.js -o output ，返回： 'sablejs' 不是内部或外部命令，也不是可运行的程序
改为执行 node cli.js -i example\fib.js -o output  返回如下：
------------------------------------------------------------------------------------
D:\Prg\npm\sablejs\node_modules\nodejs-file-downloader\Download.js:265
        for await (let chunk of stream) {
            ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\OwenWorks\npm\sablejs\node_modules\nodejs-file-downloader\Downloader.js:3:18)
------------------------------------------------------------------------------------

是我哪个步骤不对吗

**Comment by ZengOwen** [comment]
解决了npm 的prefix的Path后，已可执行 sablejs, 但执行时报错，
如 sablejs -v:

D:\Prg\npm\sablejs>sablejs -v
module.js:549
    throw err;
    ^

Error: Cannot find module 'enquirer'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Users\AppData\Roaming\npm\node_modules\sablejs\bin\sablejs:2:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
